Create erb wizard from
prophetsfall/wizards_reviews pull request #19
Opened 2018-01-25 21:23 UTC by iBrooks

Added an erb form to add a new wizard
removed obsolete api endpoints
removed obsolete api tests
updated show to operate off of id not name

2018-01-25 21:36 UTC, dpickett requested changes

2018-01-25 21:36 UTC, dpickett commented on app/controllers/api/v1/wizards_controller.rb
> +    params.require(:wizard).permit(:id, :name, :description, :img_url, :creator_id)
we do not want to allow the user to provide the id / primary key here. this should be left out of strong params

2018-01-25 21:36 UTC, dpickett commented on app/controllers/wizards_controller.rb
> +  def new
consider a blank line between each method

2018-01-25 21:36 UTC, dpickett commented on app/controllers/wizards_controller.rb
> +        flash[:notice] = 'Wizards added successfully'
convention wise, we like the `flash` to come before the redirect.

2018-01-25 21:36 UTC, dpickett commented on app/javascript/react/components/WizardShow.js
> +  <div>
consider indenting this `<div>` for readability

2018-01-25 21:36 UTC, dpickett commented on app/models/wizard.rb
> +  def to_param
consider a line break above this line

2018-01-25 21:36 UTC, dpickett commented on db/migrate/20180124144439_add_name_too_users.rb
> +    add_column :users, :user_name, :string, null: false, default: "user"
why set a default here? I wouldn't recommend it.

2018-01-25 21:36 UTC, dpickett commented on spec/features/user_sumbits_new_wizard_spec.rb
> +  scenario 'user submits invalid form' do
these tests should be completed

2018-01-26 15:58 UTC, prophetsfall commented
We've cleaned this up pull request. Please review.

2018-01-26 16:09 UTC, dpickett requested changes

2018-01-26 16:09 UTC, dpickett commented on app/controllers/wizards_controller.rb
> +      @wizard = Wizard.new(wizards_params.merge({ creator_id: current_user.id }))
I would prefer:

```ruby
@wizard = Wizard.new(wizards_params)
@wizard.user = current_user
```

2018-01-26 16:09 UTC, dpickett commented on app/views/wizards/new.html.erb
> + <div id='error_explanation'>
use double quotes for HTML attribute values

2018-01-26 16:34 UTC, prophetsfall commented
Requested changes have been completed.

2018-01-26 17:46 UTC, prophetsfall commented
Ok, this should be good to go now.

2018-01-26 18:40 UTC, dpickett commented on app/controllers/wizards_controller.rb
> +      @wizard.creator_id = current_user.id
you could remove the id here - I find it to be more expressive

`@wizard.creator = current-user`

2018-01-26 18:41 UTC, dpickett approved these changes

2018-01-26 18:41 UTC, merged